"""Generate the radar Model-B configs (1a, 1b) from configs/config.yml so that every
setting not listed here stays identical to the gauge baseline.

    python configs/make_radar_configs.py
"""
import copy
import os

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
SCI = "/sci/labs/efratmorin"
RADAR = f"{SCI}/ariel.monzon/SR_radar"
EXTRACTION = f"{RADAR}/IMS_SR_adjusted_basin_hourly_v1"
INPUTS = f"{EXTRACTION}/model_inputs_v1"
RADAR_FEATURES = ["radar_mean_mm", "radar_max_mm", "radar_p90_mm", "radar_wet_frac", "radar_std_mm"]

COMMON = {
    # --- data ---
    "radar_extraction_dir": EXTRACTION,
    "processed_timeseries_dir": f"{INPUTS}/timeseries",
    "availability_report_file": f"{INPUTS}/availability_report.csv",
    "radar_features": RADAR_FEATURES,
    # static attributes: Liron's normalized file (same statics as the gauge baseline)
    "normalized_static_attributes_file": f"{SCI}/liron.haris/FlashFloodsIsrael/data/processed/static/static_attributes_normalized.csv",
    # flood thresholds used by test.py (hit rates / events): Liron's combined return-period file
    "hourly_flow_return_periods_combined": f"{SCI}/liron.haris/FlashFloodsIsrael/data/processed/return_periods/new_return_periods.csv",
    "use_basin_splits": False,
    # --- sample rules (radar gap handling, see RADAR_INTEGRATION_REPORT.md) ---
    "seq_length": 72,
    "forecast_lead_times": [0, 1, 2, 3],
    "gap_max_run": 2,
    "gap_max_total": 6,
    "sample_filter_column": "window_ok",
    "require_contiguous_windows": True,
    # --- Model B periods (hydrological years, pipeline clock) ---
    "train_periods": [
        {"start_date": "2012-10-01 08:00:00", "end_date": "2016-09-30 07:00:00"},
        {"start_date": "2019-10-01 08:00:00", "end_date": "2020-09-30 07:00:00"},
        {"start_date": "2021-10-01 08:00:00", "end_date": "2023-09-30 07:00:00"},
    ],
    "validation_start_date": "2020-10-01 08:00:00",
    "validation_end_date": "2021-09-30 07:00:00",
    "test_start_date": "2016-10-01 08:00:00",   # = Liron's test period -> her trained gauge model is the baseline
    "test_end_date": "2019-09-30 07:00:00",
    "run_dir": f"{RADAR}/runs/",
}

RUNS = {
    "SRradar_B_mean_mask": {"dynamic_inputs": ["radar_mean_mm", "radar_mask"]},
    "SRradar_B_allstats_mask": {"dynamic_inputs": RADAR_FEATURES + ["radar_mask"]},
}


def main():
    base = yaml.safe_load(open(os.path.join(HERE, "config.yml"), encoding="utf-8"))
    base.pop("wandb_api_key", None)            # never copy the key; use `wandb login` / WANDB_API_KEY
    for name, extra in RUNS.items():
        cfg = copy.deepcopy(base)
        cfg.update(COMMON)
        cfg.update(extra)
        cfg["experiment_name"] = name
        cfg.pop("cumulative_rain_windows", None)   # no weekly total in the radar runs (for now)
        path = os.path.join(HERE, f"{name}.yml")
        with open(path, "w", encoding="utf-8") as f:
            f.write(f"# GENERATED by configs/make_radar_configs.py from config.yml - edit the generator, not this file.\n")
            yaml.safe_dump(cfg, f, sort_keys=False, allow_unicode=True)
        print("wrote", path)


if __name__ == "__main__":
    main()
