"""Generate the radar Model-B configs (1a, 1b) from configs/config.yml so that every
setting not listed here stays identical to the gauge baseline.

    python configs/make_radar_configs.py
"""
import copy
import os

import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
SCI = "/sci/labs/efratmorin"
RADAR = f"{SCI}/ariel.monzon/SR_radar"
EXTRACTION = f"{RADAR}/IMS_SR_adjusted_basin_hourly_v1"
INPUTS = f"{EXTRACTION}/model_inputs_v1"
RADAR_FEATURES = ["radar_mean_mm", "radar_max_mm", "radar_p90_mm", "radar_wet_frac", "radar_std_mm",
                  "radar_volume_m3"]   # rain amount over the basin (m3/h), from extraction v2 on

COMMON = {
    # --- data ---
    "radar_extraction_dir": EXTRACTION,
    "processed_timeseries_dir": f"{INPUTS}/timeseries",
    "availability_report_file": f"{INPUTS}/availability_report.csv",
    "radar_features": RADAR_FEATURES,
    # static attributes: Liron's normalized file + basins missing from it, normalized with her constants
    # (built once by src/extend_static_attributes.py; evidence in RADAR_INTEGRATION_REPORT.md)
    "static_source_dir": f"{SCI}/liron.haris/FlashFloodsIsrael/data/processed/static",
    "static_extend_basins": ["il_14115", "il_17110", "il_17117", "il_18131"],
    # Liron's raw statics on the cluster lack these basins; the full 95-basin raw file (floods/data/static/
    # static_attributes_nh.csv) is uploaded here and must agree with hers on all shared basins
    "static_extra_raw_file": f"{RADAR}/static/static_attributes_nh_all95.csv",
    "normalized_static_attributes_file": f"{RADAR}/static/static_attributes_normalized_plus4.csv",
    # flow-QC exclusion: il_17123 - 2013-01-08 official peak 99 m3/s but hourly series 0.0; max 0.42 m3/s 2012-23
    "exclude_basins": ["il_17123"],
    # flood thresholds used by test.py (hit rates / events): Liron's combined return-period file
    "hourly_flow_return_periods_combined": f"{SCI}/liron.haris/FlashFloodsIsrael/data/processed/return_periods/new_return_periods.csv",
    "use_basin_splits": False,
    # basin lists (repo-relative): all 52 radar training basins / the 48 also in Liron's statics,
    # used as test_basin_file so model_compare_test.py can compare radar and gauge models fairly
    "train_basin_file": "configs/basins_radar_52.txt",
    "test_basin_file": "configs/basins_radar_shared48.txt",
    # --- sample rules (radar gap handling, see RADAR_INTEGRATION_REPORT.md) ---
    "seq_length": 72,
    "forecast_lead_times": [0, 1, 2, 3],
    "gap_max_run": 2,
    "gap_max_total": 6,
    "sample_filter_column": "window_ok",
    "require_contiguous_windows": True,
    # --- Model B periods (hydrological years, pipeline clock) ---
    "train_periods": [
        {"start_date": "2012-10-01 08:00:00", "end_date": "2016-09-30 07:00:00"},
        {"start_date": "2019-10-01 08:00:00", "end_date": "2020-09-30 07:00:00"},
        {"start_date": "2021-10-01 08:00:00", "end_date": "2023-09-30 07:00:00"},
    ],
    "validation_start_date": "2020-10-01 08:00:00",
    "validation_end_date": "2021-09-30 07:00:00",
    "test_start_date": "2016-10-01 08:00:00",   # = Liron's test period -> her trained gauge model is the baseline
    "test_end_date": "2019-09-30 07:00:00",
    "run_dir": f"{RADAR}/runs/",
    # flood-event threshold for predicted events (Liron's metric code; 2 = 2-year return period,
    # her scripts' default - to be confirmed against her configs)
    "prediction_threshold": 2,
    # hydrograph rain bars: radar basin mean (gaps left blank)
    "rain_overlay_column": "radar_mean_mm",
}

LEADS = [0, 1, 2, 3]

RUNS = {
    "SRradar_B_mean_mask": {"dynamic_inputs": ["radar_mean_mm", "radar_mask"]},
    "SRradar_B_allstats_mask": {"dynamic_inputs": RADAR_FEATURES + ["radar_mask"]},
}


def main():
    base = yaml.safe_load(open(os.path.join(HERE, "config.yml"), encoding="utf-8"))
    base.pop("wandb_api_key", None)            # never copy the key; use `wandb login` / WANDB_API_KEY
    # one model per lead time (as in Liron's setup): <variant>_L<k> with forecast_lead_times [k]
    for variant, extra in RUNS.items():
        for lead in LEADS:
            name = f"{variant}_L{lead}"
            cfg = copy.deepcopy(base)
            cfg.update(COMMON)
            cfg.update(extra)
            cfg["forecast_lead_times"] = [lead]
            cfg["experiment_name"] = name
            # per-run event list (the default ./data/... path is shared by parallel runs)
            cfg["find_flood_events_output"] = f"{RADAR}/runs/{name}/flood_events_all_basins.csv"
            cfg.pop("cumulative_rain_windows", None)   # no weekly total in the radar runs (for now)
            path = os.path.join(HERE, f"{name}.yml")
            with open(path, "w", encoding="utf-8") as f:
                f.write("# GENERATED by configs/make_radar_configs.py from config.yml - edit the generator, not this file.\n")
                yaml.safe_dump(cfg, f, sort_keys=False, allow_unicode=True)
            print("wrote", path)
            # eval copy for Liron's comparison tools: in train.py checkpoint_path means "resume from",
            # so it must only be set in evaluation configs
            ev = dict(cfg, checkpoint_path=f"{RADAR}/runs/{name}/best_model.pt")
            os.makedirs(os.path.join(HERE, "eval"), exist_ok=True)
            with open(os.path.join(HERE, "eval", f"{name}.yml"), "w", encoding="utf-8") as f:
                f.write("# GENERATED eval config (checkpoint_path set) - for test/quick_test/model_compare_* only.\n")
                yaml.safe_dump(ev, f, sort_keys=False, allow_unicode=True)


if __name__ == "__main__":
    main()
