program: src/run_sweep.py
project: flash-floods-israel
method: bayes
metric:
  goal: minimize
  name: val_loss
parameters:
  hidden_size:
    values: [32, 64, 128, 256]
  output_dropout:
    distribution: uniform
    min: 0.1
    max: 0.5
  initial_lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  batch_size:
    values: [64, 128, 256, 512]
  clip_gradient_norm:
    values: [0.5, 1.0, 2.0, 5.0]
